 <!-- Javascript -->
    <script type="text/javascript" src="appAssets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="appAssets/js/jquery.min.js"></script>
    <script type="text/javascript" src="appAssets/js/swiper-bundle.min.js"></script>
    <script type="text/javascript" src="appAssets/js/carousel.js"></script>
    <script type="text/javascript" src="appAssets/js/plugin.js"></script>
    <script type="text/javascript" src="appAssets/js/jquery.nice-select.min.js"></script>
    <script type="text/javascript" src="appAssets/js/rangle-slider.js"></script>
    <script type="text/javascript" src="appAssets/js/countto.js"></script>
    <script type="text/javascript" src="appAssets/js/shortcodes.js"></script>
    <script type="text/javascript" src="appAssets/js/animation_heading.js"></script>
    <script type="text/javascript" src="appAssets/js/lazysize.min.js"></script>
    <script type="text/javascript" src="appAssets/js/main.js"></script>
